id: P2E8B4304
initial_creation_type: ocr
source_metadata:
  volumes:
    1bf59df43cc6410887d202855f1ca6b3:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སྤེལ་མར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
